class KeysMap:
    """Selenium key map for Playwright"""

    NULL = ""
    CANCEL = "Cancel"  # ^break
    HELP = "Help"
    BACKSPACE = "Backspace"
    BACK_SPACE = BACKSPACE
    TAB = "TAB"
    CLEAR = "Clear"
    RETURN = "Return"
    ENTER = "Enter"
    SHIFT = "Shift"
    LEFT_SHIFT = SHIFT
    CONTROL = "Control"
    LEFT_CONTROL = CONTROL
    ALT = "Alt"
    LEFT_ALT = ALT
    PAUSE = "Pause"
    ESCAPE = "Escape"
    SPACE = "Space"
    PAGE_UP = "PageUp"
    PAGE_DOWN = "PageDown"
    END = "End"
    HOME = "Home"
    LEFT = "Left"
    ARROW_LEFT = LEFT
    UP = "Up"
    ARROW_UP = UP
    RIGHT = "Right"
    ARROW_RIGHT = RIGHT
    DOWN = "Down"
    ARROW_DOWN = DOWN
    INSERT = "Insert"
    DELETE = "Delete"
    # SEMICOLON = ""
    # EQUALS = "\ue019"

    NUMPAD0 = "Digit0"  # number pad keys
    NUMPAD1 = "Digit1"
    NUMPAD2 = "Digit2"
    NUMPAD3 = "Digit3"
    NUMPAD4 = "Digit4"
    NUMPAD5 = "Digit5"
    NUMPAD6 = "Digit6"
    NUMPAD7 = "Digit7"
    NUMPAD8 = "Digit8"
    NUMPAD9 = "Digit9"
    MULTIPLY = "Multiply"
    ADD = "Add"
    SEPARATOR = "Separator"
    SUBTRACT = "Subtract"
    DECIMAL = "Decimal"
    DIVIDE = "Divide"

    F1 = "F1"  # function  keys
    F2 = "F2"
    F3 = "F3"
    F4 = "F4"
    F5 = "F5"
    F6 = "F6"
    F7 = "F7"
    F8 = "F8"
    F9 = "F9"
    F10 = "F10"
    F11 = "F11"
    F12 = "F12"

    META = "Meta"
    COMMAND = "Command"
    ZENKAKU_HANKAKU = "ZenkakuHankaku"